In [ ]:
import numpy as np

In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((3,2))

In [ ]:
np.arange(0,10,2)

In [ ]:
np.random.rand(2,2)

In [ ]:
import matplotlib.pyplot as plt
arr = np.random.rand(10)
plt.plot(arr)
plt.show()

In [ ]:
arr = np.array([1,2,3,4])
arr * arr

In [ ]:
mat = np.array([[2,3],[4,9]])
np.dot(mat, mat)

In [ ]:
# indexing
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr_2d[0]
arr_2d[0,2]

In [ ]:
arr_2d[0:3:2,0]

In [ ]:
arr_3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

arr_3d[0,1,1]

#### 3D array implementation and slicing
- arr_3d = np.arange(1, 25)
- arr.reshape(2, 3, 4)  # 3D shape: (depth=2, rows=3, cols=4)

#### (depth=, rows=, cols=) for 3D arrays


In [ ]:
new_arr = np.random.randint(1, 20, (3,3,2))
new_arr

In [94]:
arr_3d = np.arange(25)
arr_3d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
new_arr[:1, 1:, 1]

In [ ]:
arr4x4 = np.random.randint(1,15, (4,4))
arr4x4

In [ ]:
arr4x4[:, 3:]
np.dot(arr2x3, arr2x3.T)
arr4x4[:2, 2:]

In [ ]:
for i in arr_2d.flat:
    print(i, end = " ")

arr_2d.shape 
arr_2d.ndim
arr_2d.size
arr_2d.dtype
arr_2d.itemsize
arr_2d.nbytes
arr_2d.T

In [96]:
arr = np.arange(1,9)
arr.shape
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [106]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

Mini Challenge for You:

- Create an identity matrix of size 4x4.

- Create another 4x4 random integer matrix.

- Concatenate them vertically (axis=0).

- Then take its transpose.

In [109]:
#challenge
iden = np.eye(4)
rand4x4 = np.random.randint(1, 50, (4,4))
newArr = np.concatenate((iden, rand4x4), axis=0)
newArr.T

array([[ 1.,  0.,  0.,  0., 31., 12., 29., 31.],
       [ 0.,  1.,  0.,  0., 20., 38., 22., 12.],
       [ 0.,  0.,  1.,  0., 19., 31., 28., 37.],
       [ 0.,  0.,  0.,  1.,  5., 34., 34., 18.]])

UsageError: %%timeit is a cell magic, but the cell body is empty. Did you mean the line magic %timeit (single %)?
