In [1]:
import numpy as np

In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((3,2))

In [ ]:
np.arange(0,10,2)

In [ ]:
np.random.rand(2,2)

In [ ]:
import matplotlib.pyplot as plt
arr = np.random.rand(10)
plt.plot(arr)
plt.show()

In [ ]:
arr = np.array([1,2,3,4])
arr * arr

In [ ]:
mat = np.array([[2,3],[4,9]])
np.dot(mat, mat)

In [ ]:
# indexing
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr_2d[0]
arr_2d[0,2]

In [ ]:
arr_2d[0:3:2,0]

In [ ]:
arr_3d = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

arr_3d[0,1,1]

#### 3D array implementation and slicing
- arr_3d = np.arange(1, 25)
- arr.reshape(2, 3, 4)  # 3D shape: (depth=2, rows=3, cols=4)

#### (depth=, rows=, cols=) for 3D arrays


In [ ]:
new_arr = np.random.randint(1, 20, (3,3,2))
new_arr

In [ ]:
arr_3d = np.arange(25)
arr_3d

In [ ]:
new_arr[:1, 1:, 1]

In [ ]:
arr4x4 = np.random.randint(1,15, (4,4))
arr4x4

In [ ]:
arr4x4[:, 3:]
np.dot(arr2x3, arr2x3.T)
arr4x4[:2, 2:]

In [ ]:
for i in arr_2d.flat:
    print(i, end = " ")

arr_2d.shape 
arr_2d.ndim
arr_2d.size
arr_2d.dtype
arr_2d.itemsize
arr_2d.nbytes
arr_2d.T

In [ ]:
arr = np.arange(1,9)
arr.shape
arr.reshape(2,4)

In [ ]:
np.linspace(0, 20, 5)

Mini Challenge for You:

- Create an identity matrix of size 4x4.

- Create another 4x4 random integer matrix.

- Concatenate them vertically (axis=0).

- Then take its transpose.

In [ ]:
#challenge
iden = np.eye(4)
rand4x4 = np.random.randint(1, 50, (4,4))
newArr = np.concatenate((iden, rand4x4), axis=0)
newArr.T

###  BroadCasting
- Broadcasting allows numpy to perform Operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape
> Rules
- The dimensions have the same size(from right to left)
- OR, one of the dimensions have the size of 1

In [ ]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[1],[2],[3],[4],[5]])
arr1.shape
arr2.shape
arr1 * arr2

In [ ]:
# Example 1: (3,2) + (2,)
a = np.ones((3,2))
b = np.array([1,2])
print((a+b).shape)  # (3,2) ✅

# Example 2: (4,3) + (3,)
a = np.ones((4,3))
b = np.array([1,2,3])
print((a+b).shape)  # (4,3) ✅

# Example 3: (2,3) + (2,1)
a = np.ones((2,3))
b = np.array([[1],[2]])
print((a+b).shape)  # (2,3) ✅

# Example 4: (3,2) + (3,) 
a = np.ones((3,2))
b = np.array([1,2,3])
print(a+b)  # ERROR ❌

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T.shape)

### Exercises
Create a 4x4 array of random integers (1–20). Print only the last column.

Generate an array of shape (3,3) with values from 0 to 8 using np.arange.

Create a (2,3) array of ones and add [10,20,30] to it using broadcasting.

Compute the mean and standard deviation of an array [5,10,15,20].

Reshape a 1D array of 12 numbers into a (3,4) 2D array.

Split an array [0,1,2,3,4,5] into 3 equal parts.

Concatenate a (2,2) array of ones with a (2,2) array of zeros vertically.

Generate 10 numbers evenly spaced between -1 and 1.

For arr = np.array([1,2,3]), compute the cumulative sum.

Verify if the following two arrays can be broadcast together:

A: shape (3,1)

B: shape (1,4)

In [ ]:
#1
arr = np.random.randint(1, 20, (4,4))
print(arr[:, 3:])
#2
arrArange = np.arange(0, 9).reshape(3,3)
print(arrArange)
#3
arrOnes = np.ones((2, 3))
arr = np.array([10, 20, 30])
print(arrOnes + arr)
#4
arr = np.array([5,10,15,20])
print(np.mean(arr))
print(np.std(arr))
#5
arr = np.ones(12)
print(arr.reshape(3,4))
#6
arr = np.array([0,1,2,3,4,5])
print(np.split(arr, 3))
#7
arr1 = np.ones((2,2))
arr2 = np.zeros((2,2))
print(np.concatenate((arr1, arr2)))
#8
arr = np.linspace(-1, 1, 10)
print(arr)
#9
arr = np.array([1,2,3])
print(np.cumsum(arr))
#10
arr1 = np.random.rand(3,1)
arr2 = np.random.rand(1,4)
print(arr1 * arr2) # yes, they broadcast together 


In [ ]:
# Advanced Maskingg\

#np.where(condition, value_if_true, value_if_false)

arr = np.array([[3, 2, 4],
                [3, 1, 5],
                [0, 3, 2]])
np.where(arr == 3, 0, arr)

In [2]:
# Advanced Indexing

In [10]:
arr2d = np.random.randint(1,10,(3,3))
arr2d

array([[5, 5, 8],
       [4, 1, 6],
       [1, 7, 7]], dtype=int32)

In [11]:
arr2d[:, [0,2]]

array([[5, 8],
       [4, 6],
       [1, 7]], dtype=int32)

In [43]:
arr2d[0:10:2,[0,1,2]] 

array([[5, 5, 8],
       [1, 7, 7]], dtype=int32)

In [54]:
arr2d[[True, False, True],[True, False, True]]

array([5, 7], dtype=int32)

In [45]:
arr = [0,1,2,3,4,5,6,7,8,9]
len(arr)

10

[0, 2, 4]